### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-c#1]
@tzvetkoff I could use your help on some of these (like C) 👀

**Comment by tzvetkoff** [comment]
@4kimov, sorry for being quiet lately - 8m in vacation until Aug 19.
The C version is mostly done, minus the UTF8 support, which I started adding literally 2 days ago using utf8proc.
The tricky part was to find a way to build it locally and statically, so libsquids.so doesn't introduce additional dependencies.
Anyway, I hope I'll have the time to finish it this Sunday.

**Comment by 4kimov** [comment]
@tzvetkoff Ah cool, thanks for the heads up and the work-in-progress. Didn't know you were on a vacation, enjoy! A few minor things worth noting for when you're back:

- Added [an additional check in the spec](https://github.com/sqids/sqids-spec/commit/f52b57836b0463097018f984f853b284e50a5ce4) recently to test for repeating reserved characters
- Some libs do require the use of other libraries/dependencies, so we removed the "no dependencies" bit a while back (up to you; not a problem if code needs to depend on something else)
- Lastly, as usual if you need access to anything or have questions, I'm here 👍

**Comment by tzvetkoff** [comment]
@4kimov, sorry it took me so much time to get this done but until recently I didn't have:

- The time to get everything in place, especially the UTF8/multi-char support
- Realized that UTF8 is not ultimately required now

A WiP branch will be available shortly (the moment I generate a parser-generator for the `spec` tests) and then I'll proceed with implementing the cucumbersome blocklist (it really have me headaches trying to do UTF8 regexes in C)

FWIW, most of the heavy lifting has already been done, like dynamic string allocation, encoding, now I need to finalize things like min-length and blocklist (which I almost implemented previously, before I decided to go full-UTF8.)

**Comment by 4kimov** [comment]
@tzvetkoff Thanks for the update, good to hear from you. No problem, everybody's busy, that's ok. Looking forward & let me know if I can help with anything 👍

**Comment by OctopusET** [comment]
I'm also interested in this work. @tzvetkoff If you don't mind opening your WIP branch, I'd like to start from there.

**Comment by tzvetkoff** [comment]
Took me a little more than I originally expected, mostly because I couldn't find the time to think it through and to adapt to the latest spec changes.

Anyway, I finished porting both the codebase and most of the tests, so... enjoy!

P.S. In the next days I'll also tag a release, I just need to think of a few more things, like:

- do we need `sqids_errno`?
- do we need dynamic string allocation or we can safely estimate encoded number length?
- automatic builds (using GitHub actions)

**Comment by 4kimov** [comment]
@OctopusET Thanks for offering to help. This is a community effort, so suggestions / PRs / etc are definitely always welcome 💪 

---

@tzvetkoff Thanks for the initial push! I'm definitely too rusty on C in order to help with your questions, but I have a few of my own for you:

1. Is there an example somewhere of the [3 repetitive code samples](https://github.com/sqids/sqids-rust#-examples) that I could use for the website?
1. If most of the tests are there, is it stable enough to update the site?

**Comment by tzvetkoff** [comment]
@4kimov, I just added the standard examples so you can use it on the website.
And yes, all _needed_ tests are ported and passing, so you can mark the C port as done.

**Comment by OctopusET** [comment]
It would be better to make this project much more portable to support different systems. I found some portability issues in these codes. Also choosing the C standard like C99 would be helpful.

Plus, I think there would be  improvements for the blocklist. Instead of having multiple API for languages.

**Comment by tzvetkoff** [comment]
@OctopusET, unless you share what "portability issues" you have found, there's not way for us to resolve them.

"Choosing the C standard..."
If you have looked at the code, it is clearly C99 (in fact `hashids.c` was also C99 because it required `<stdint.h>`) because it uses variable-length arrays heavily.
The tests might use something GNU-specific, which I can easily rewrite.

As for the multiple languages API, this is entirely *my* preference here - I personally think that the way we currently ship the blocklist is insane and we need to change this, because very soon it will explode.

That been said, all of these topics are for another discussion. Feel free to open a new issue for each relevant topic.
